import type { Villa } from './types';

export const fallbackVillas: Villa[] = [
  {
    id: 1,
    name: 'Garden Pool Villa',
    slug: 'garden-pool-villa',
    roomNumber: 'GV-01',
    roomType: 'Pool Villa',
    description: 'A one-bedroom garden villa with a private pool, shaded terrace, and open-air living room.',
    imageUrl: '/images/nhu-garden-pool-villa.jpg',
    pricePerNight: 450,
    capacity: 2,
    bedrooms: 1,
    isAvailable: true,
    amenities: [{ name: 'Private pool' }, { name: 'Breakfast service' }, { name: 'Garden terrace' }],
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: 2,
    name: 'Terrace Family Villa',
    slug: 'two-bedroom-family-villa',
    roomNumber: 'TF-02',
    roomType: 'Family Villa',
    description: 'Two quiet bedrooms, generous living space, and a terrace prepared for slow family days.',
    imageUrl: '/images/nhu-villa-interior.jpg',
    pricePerNight: 720,
    capacity: 4,
    bedrooms: 2,
    isAvailable: true,
    amenities: [{ name: 'Open-air living' }, { name: 'High-speed Wi-Fi' }, { name: 'Housekeeping' }],
    rating: 4.8,
    reviewCount: 27,
  },
  {
    id: 3,
    name: 'Hillside Residence',
    slug: 'hillside-residence-private-pool',
    roomNumber: 'HR-03',
    roomType: 'Residence',
    description: 'A larger private residence for hosted dinners, longer retreats, and sunset pool rituals.',
    imageUrl: '/images/nhu-infinity-pool.jpg',
    pricePerNight: 1150,
    capacity: 6,
    bedrooms: 3,
    isAvailable: true,
    amenities: [{ name: 'Concierge planning' }, { name: 'Private pool' }, { name: 'Airport transfer' }],
    rating: 4.95,
    reviewCount: 19,
  },
  {
    id: 4,
    name: 'Signature Four Bedroom Estate',
    slug: 'signature-four-bedroom-estate',
    roomNumber: 'SE-04',
    roomType: 'Signature',
    description: 'The largest estate in our collection, offering panoramic views, four bedrooms, and complete privacy.',
    imageUrl: '/images/nhu-private-dining.jpg',
    pricePerNight: 2500,
    capacity: 8,
    bedrooms: 4,
    isAvailable: true,
    amenities: [{ name: 'Open-air living' }, { name: 'Private pool' }, { name: 'High-speed Wi-Fi' }],
    rating: 5.0,
    reviewCount: 12,
  },
  {
    id: 104,
    name: 'Water Courtyard Villa',
    slug: 'water-courtyard-villa',
    roomNumber: 'WC-04',
    roomType: 'Pool Villa',
    description: 'A courtyard villa arranged around water, linen, warm stone, and late breakfast rituals.',
    imageUrl: '/images/nhu-hero-villa.jpg',
    pricePerNight: 560,
    capacity: 2,
    bedrooms: 1,
    isAvailable: false,
    amenities: [{ name: 'Private pool' }, { name: 'Garden terrace' }, { name: 'Breakfast service' }],
    rating: 4.85,
    reviewCount: 31,
  },
  {
    id: 105,
    name: 'Forest Pavilion',
    slug: 'forest-pavilion',
    roomNumber: 'FP-05',
    roomType: 'Pavilion',
    description: 'A quiet pavilion for couples who want deep shade, forest sound, and a smaller footprint.',
    imageUrl: '/images/nhu-location-landscape.jpg',
    pricePerNight: 390,
    capacity: 2,
    bedrooms: 1,
    isAvailable: true,
    amenities: [{ name: 'High-speed Wi-Fi' }, { name: 'Housekeeping' }, { name: 'Garden terrace' }],
    rating: 4.7,
    reviewCount: 22,
  },
];
