-- ============================================================
-- PostgreSQL Migration - V1
-- Convert AUTO_INCREMENT to SERIAL/BIGSERIAL for PostgreSQL
-- ============================================================

-- Users
ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Room types
ALTER TABLE room_types ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Amenities
ALTER TABLE amenities ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Rooms
ALTER TABLE rooms ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Vouchers
ALTER TABLE vouchers ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Promotions
ALTER TABLE promotions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Bookings
ALTER TABLE bookings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Booking status transitions
ALTER TABLE booking_status_transitions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Reviews
ALTER TABLE reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Wishlists
ALTER TABLE wishlists ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Payments
ALTER TABLE payments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Notifications
ALTER TABLE notifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Audit logs
ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- FAQ items
ALTER TABLE faq_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Blogs
ALTER TABLE blogs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Chat messages
ALTER TABLE chat_messages ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Contact messages
ALTER TABLE contact_messages ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
